# variables

In [ ]:
car=23
print(car)

In [ ]:
2+5

In [1]:
*= 5
print(*)
# variable we cannot store symbol,starting with number,no gaps but we use _

SyntaxError: invalid syntax (262324141.py, line 1)

In [ ]:
you_tube=67
print(you_tube)

In [ ]:
car=65
CAR=89
print(car)

In [ ]:
print(CAR)
# python is a case sensitive

In [ ]:
xcar$=56
print(xcar$)

# keyword

In [ ]:
import keyword
keyword.kwlist
# this keywords cannot be usrd as variable name
# keyword is a library

# identifiers

identifiers used to variable,functions,class, structure,union
it is not a keyword

# operators

2+3=5
2 and 3 are operands and = is a operator

# Arithmemtic operator



In [3]:
a= 10
b= 20
a, b

(10, 20)

In [ ]:
a+b

In [ ]:
a-b

In [ ]:
a*b

In [4]:
a/b

0.5

In [5]:
# floor division
a//b
#0.5 it take lowest integer (round value)

0

In [6]:
a= 100
b = 5

a//b

20

In [ ]:
b % a
# remainder

In [ ]:
a**b
# 10 power 20

# comparison operator


In [ ]:
a==b, a!=b, a>b

# = assign operator
# == comparison operator

In [ ]:
a<b, a>=b, a<=b, a!=b

# assignment operator


In [ ]:
a = 10
b = 20

c= a + b
print(c)

c += b # c=c+b
c

In [ ]:
c -= b
c

In [ ]:
c *= b
c

In [ ]:
c /= b
c

In [ ]:
c %= b
c

In [ ]:
c **= b
c

In [ ]:
c //= b
c

In [ ]:
a, b, c = 1, 3, 5 # sequential order 
print(a, b, c)
a, b, c

# logical operator


In [ ]:
a = 3; b = 2; c = 0

a and b, b and c, c and a

# left side value non zero assign right value

In [1]:
a=4
b=9
c=0

print(a and b)
print(b and c)
print(c and a)
print('orange' and 'apple')
print(' ' and 'apple')

9
0
0
apple
apple


In [7]:
# or operator(a left side value is non zero then return non zero or right side value)
a = 3; b=2;c =0
c or b, a or c, c or a, a or b, 
print((0 and 5)or 3)


3


In [10]:
c = 0 
b = 1

c or b

1

# identity operator


In [11]:
'y' is 'python', 1 is 1, 0 is 1 # identity operator (is,not is)

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\annam\AppData\Local\Temp\ipykernel_16116\3143187422.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  'y' is 'python', 1 is 1, 0 is 1 # identity operator (is,not is)
C:\Users\annam\AppData\Local\Temp\ipykernel_16116\3143187422.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  'y' is 'python', 1 is 1, 0 is 1 # identity operator (is,not is)
C:\Users\annam\AppData\Local\Temp\ipykernel_16116\3143187422.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  'y' is 'python', 1 is 1, 0 is 1 # identity operator (is,not is)


(False, True, False)

In [ ]:
'python' is 'Python', 1 is 0

In [ ]:
1 is not 1, "hi hello" is not "hello hi"

In [ ]:
c = (2 + 4j)
print(c)
type(c)

In [ ]:
type(True), type(False)

# membership operator



In [ ]:
# membership operator (in, not in)

"y" in "Python", "l" in "Python"

In [ ]:
"p" in "Python" , "P" not in "python" # case sensitive

# python data types

In [ ]:
# operator should be pemdas(paranthesis,exanpanantion,multiply,division,add,sub)
# python 5 data types 1 number 2 boolean 3 sets{2,4,6} 4 dict{1;'a', 2;'b'} 5 sequence, 
# in sequence there is 3 type string,list,tuple


In [ ]:
# integer

print(1)
print(5 + 8)
print(12 * 8)
a = 1
type(a)

In [ ]:
#  float
print(6.88)
print(6.43 + 3.34)
t= 99.87
type(t)

In [ ]:
# boolean
# true = 1 , False = 0

True + False

In [ ]:
False + False

In [ ]:
True + False + True + True

In [ ]:
print (type(True))
type(False)

In [ ]:
# list
# is a sequence of items
# it denoted []
# it contain different data types
# values are mutable(it changed)

In [21]:
list1 = ["annamalai", "gopi24", 2022, 2023]
print(list1)
print(len(list1))
list1[1] = 'usha'
print(list1)
list1.insert(1, 'nilani')
print(list1)
list1.remove(2022)
print(list1)
list1.extend('appa')
list1

['annamalai', 'gopi24', 2022, 2023]
4
['annamalai', 'usha', 2022, 2023]
['annamalai', 'nilani', 'usha', 2022, 2023]
['annamalai', 'nilani', 'usha', 2023]


['annamalai', 'nilani', 'usha', 2023, 'a', 'p', 'p', 'a']

In [ ]:
# by using index number
print(list1[0])
print(list1[3])
print(list1[:3])
print(list1[0:])

In [ ]:
# reversing list
print(list1[::-1])


In [ ]:
# function in list data types

#append- add new elements in the list

list1.append("amma")
print(list1)

In [ ]:
list1.remove(alist)
print(list1)

In [23]:
# pop- remove the last element

csk=['dhoni', 'jaddu', "conway", 'dube', 'rayadu']
print(csk.pop())
print(csk)

print(csk.pop(1))
print(csk)

rayadu
['dhoni', 'jaddu', 'conway', 'dube']
jaddu
['dhoni', 'conway', 'dube']


In [24]:
# insert- a value from index number

csk.insert(1, "ruttu")
print(csk)

csk.append("santener")
print(csk)

['dhoni', 'ruttu', 'conway', 'dube']
['dhoni', 'ruttu', 'conway', 'dube', 'santener']


In [25]:
#extend- extend the two list one after another

rcb = ["duplesis", "kohli", "maxwell", "siraj"]

print(csk * 2)
print(csk + rcb)
csk.extend(rcb)
print(csk)

['dhoni', 'ruttu', 'conway', 'dube', 'santener', 'dhoni', 'ruttu', 'conway', 'dube', 'santener']
['dhoni', 'ruttu', 'conway', 'dube', 'santener', 'duplesis', 'kohli', 'maxwell', 'siraj']
['dhoni', 'ruttu', 'conway', 'dube', 'santener', 'duplesis', 'kohli', 'maxwell', 'siraj']


In [ ]:
mi=["rohit", "ishan", "surya"]
print(csk.append(mi))

In [26]:
csk.remove(rcb)
print(csk)

ValueError: list.remove(x): x not in list

In [32]:
csk=['dhoni', 'jaddu', "conway", 'dube', 'rayadu']
mi = ["rohit", "ishan", "surya"]
ipl = csk + mi
print(ipl)
ipl.remove('rohit')
print(ipl)

['dhoni', 'jaddu', 'conway', 'dube', 'rayadu', 'rohit', 'ishan', 'surya']
['dhoni', 'jaddu', 'conway', 'dube', 'rayadu', 'ishan', 'surya']


In [ ]:
csk

In [38]:
family = ["appa", "amma", "anna", "akka"]
tour = ["usa", 'goa', "uk"]
tour.extend(family)
print(family)
tour.sort(reverse = True)
tour

['appa', 'amma', 'anna', 'akka']


['usa', 'uk', 'goa', 'appa', 'anna', 'amma', 'akka']

In [ ]:
tour = ["usa", 'goa', "uk"]
print(tour)
tour.append('india')
print(tour)
tour.remove('uk')
print(tour)

In [ ]:
tour.reverse()
print(tour)

In [61]:
a=[1, 4, 5, 6]
b = [67, 54, 56, 78]
print(a + b)

del b[0:2]
b

a.clear()
a


[1, 4, 5, 6, 67, 54, 56, 78]


[]

In [40]:
# sort- ascending or desceding

alist = [23, 34, 45, 56, 67, 11, 45]
print(alist.sort())
print(alist)

alist.sort(reverse = True)
print(alist)

None
[11, 23, 34, 45, 45, 56, 67]
[67, 56, 45, 45, 34, 23, 11]


In [43]:
a = [11, 23, 45, 67, 78, 12]
a.sort(reverse = False)
a

[11, 12, 23, 45, 67, 78]

In [41]:
# another way sorted list
blist = [11, 56, 98, 45]
sorted_list= sorted(blist)
print(sorted_list)
sorted_list.reverse()
print(sorted_list)

[11, 45, 56, 98]
[98, 56, 45, 11]


In [44]:
# count the value iin he list
csk = ['dhoni', 'conway', 'jaddu', 8, 7, 8, 98]
print(csk.count('jaddu'))
print(csk.count(8))

1
2


In [45]:
# find the value in the list
print(csk.index('jaddu'))

2


In [ ]:
# concatinate list

new_list = csk + blist
print(new_list)

In [ ]:
type(new_list)

In [ ]:
# to get detailed info about list
help(list)

In [ ]:
# SORTING

numberlist = [1, 3, 4, 6, 8, 99, 78, 65, 45, 34, 54, 1, 32, 31, 54,]
numberlist.sort()
print(numberlist)
print(len(numberlist))
print(max(numberlist))
print(min(numberlist))

In [47]:
# sorting in length

string = ['abcg', 'hijd', 'effg', 'lmi']
sorted(string)
print(string)
print(sorted(string, key=len))

['abcg', 'hijd', 'effg', 'lmi']
['lmi', 'abcg', 'hijd', 'effg']


In [48]:
print(sorted(string))

['abcg', 'effg', 'hijd', 'lmi']


In [51]:
# create our own function
def funct(l):
    return l[-1]
funct('anna')

'a'

In [ ]:
def func(k):
    return k[-2]
func(string)

In [ ]:
print(funct('abcde',))

In [ ]:
print(funct('fgh'))

In [52]:
print(sorted(string, key=funct)) # -1= d,f,g,i

['hijd', 'abcg', 'effg', 'lmi']


In [ ]:
# tuples ()
# immutable- we can't edit or write
# faster than list
# tuple can used key in dictioneries

In [ ]:
# create a tuple
tup1 = ('amma', 'appa', 'anna', 'akka', 'me')
tup2 = (1975, 1970, 1995, 1993)
print(tup1)
print(tup2)

In [ ]:
id(tup1)

In [ ]:
# create empty tuple

tup = ()
print(tup)

In [ ]:
 id(tup)
    # tuple stores different location

In [ ]:
tup1 = (50,)
print(tup1)
type(tup1)

In [54]:
tup1 = ('amma', 'appa', 'anna', 'akka', 'me')
tup2 = (1975, 1970, 1995, 1993)
print(tup1[0])
print(tup2[0:3])
tup.append(1998)

amma
(1975, 1970, 1995)


NameError: name 'tup' is not defined

In [55]:
tup1 = tup1 + tup2
print(tup1)

('amma', 'appa', 'anna', 'akka', 'me', 1975, 1970, 1995, 1993)


In [ ]:
tup1.remove()
print(tup1)

# in tupple we did not delete it is immutable

In [58]:
tup = (1,3,4,6)
tup.clear()


SyntaxError: invalid syntax (4001136527.py, line 2)

In [ ]:
help (tuple)

# sets

In [ ]:
# in sets we can store multiple variables
# sets are unindexed,unordered,mutable
# did not allow duplicates
# frozen sets are immmutable

In [103]:
# normal set

normal_set = set ([1, 2, 3])
print(normal_set)
normal_set.clear()
normal_set

{1, 2, 3}


set()

In [63]:
#add the elements

normal_set.add(4)
print(normal_set)

{1, 2, 3, 4}


In [ ]:
# frozen set
# it's unordered

frozen_set = frozenset(['a', 'b', 'c'])
print(frozen_set)

In [ ]:
 frozen_set.add('d')
    # frozen set are immutable
    

In [105]:
set1 = set()
set2 = set()
print(set1, set2)

# add the elements in set1

for i in range(1,10):
    set1.add(i)
set1    

set() set()


{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [106]:
for j in range(3,10):
    set2.add(j)
set2    

{3, 4, 5, 6, 7, 8, 9}

In [107]:
#union
set3 = set1 | set2
print("union of set1 and set2 = ", set3)

union of set1 and set2 =  {1, 2, 3, 4, 5, 6, 7, 8, 9}


In [108]:
# intersection

set4 = set1 & set2
print("intersection of set1 and set2 = ", set4)

intersection of set1 and set2 =  {3, 4, 5, 6, 7, 8, 9}


In [109]:
if set3 > set4:
    print("set3 is superset of set4")
elif set3 < set4:
    print("set3 is subset of set4")
else:
    print("set3 is same as set4")

set3 is superset of set4


In [ ]:
a=["abcd", "efgh", 'ijkl', 'monp']
def new_fun(b):
    return b[0]
new_fun(a)

a.clear()
print(a)
    

In [110]:
if set4 < set3:
    print('\n')
    if set4 > set3:
        print('annamalai')
    elif set4 < set3:
        print("dhoni")
    else:
        print('alone')



dhoni


In [111]:
set5 = set3 - set4
print("set5 is = ", set5)
print("\n") # new line

set5 is =  {1, 2}




In [112]:
# removing all the values

set5.clear()
print('set5 = ', set5)
set5

set5 =  set()


set()

In [113]:
# check if set4 and set5 are disjoint sets
if set4.isdisjoint(set5):
    print("set4 and set5 have nothing comman\n")

set8 = set([1, 3, 5])
set9 = set([1, 3, 5])

if set8.isdisjoint(set9):
    print('annamalai')



set4 and set5 have nothing comman



In [ ]:
help(set)

In [ ]:
# dictioneries{}

# dictioneries are unordered
# keys are immutable and values are mutable
# dict suport any data types and sequence does not support

In [ ]:
# accessing the values in the dictionery

dict1 = {'name': 'annamalai', 'age': 25, "bike": "ray"}
print(dict1)
print(type(dict1))
print(dict1['name'])



In [ ]:
# updating the values

dict1["height"] = 6.12
dict1['age'] = 25
dict1["school"] = 'govt school'
print(dict1)

In [ ]:
# delete the elemnts

del(dict1['bike'])
dict1

In [ ]:
# remove all enteries

dict1.clear()
dict1

In [ ]:
# delete entire dictioneries
dict1 = {'name': 'annamalai', 'age': 25, "bike": "ray"}
dict1
del(dict1)
dict1

In [ ]:
# to get all items
dict1 = {'name': 'annamalai', 'age': 25, "bike": "ray"}
dict1.items()

In [ ]:
# to get all key
dict1.keys()

In [ ]:
# to get values
dict1.values()


In [ ]:
y= dict1.items()
print(type(y))

In [ ]:
help(dict)

In [ ]:
a=[1, 3, 5, 6, 6, 98]
a.remove(5)
print(a)
a.insert(3,45)
print(a)
del a[3]
print(len(a))
sorted(a)
a.reverse()
print(a)
a
a.clear()
a

# non-numeric

In [ ]:
# strings(character,number,letters,special character)
# strings are immutable
# strings accessed index and slicing

In [1]:
name = "python"
print(name[0])
print(name[2])
print(name[0:6])
print(name[::-1])
print(name[-1])
print(name[-3:-1])

p
t
python
nohtyp
n
ho


In [2]:
print(name * 4)

pythonpythonpythonpython


In [3]:
print(name +"  "+ "Test")

python  Test


In [4]:
len(name)

6

In [ ]:
# string slicing--> (start:stop:step)

title = "the best language"
print(title[::1])
print(title[::2])
print(title[::3])
print(title[5::3])
print(title[1:10:2])
print(title[1])
print(title[:5])
print(title[1:6])

In [5]:
# update strings

var = "hello world!"
print("updated string :", var + "python")
print("updated string: ",var[:6] + "python")

updated string : hello world!python
updated string:  hello python


In [ ]:
string = "this is python"
strlist = list(string)
print(strlist)

In [6]:
# string formatting
format = '%.3f %s is $%d'
format %(2.3456,"anna",34)

'2.346 anna is $34'

In [7]:
# triple quotes

statement = """this is "annamalai" and iam "vip"."""
print(statement)
type(statement)

this is "annamalai" and iam "vip".


str

In [8]:
name = "pYtHoN"

print(name.capitalize()) #first letter capital
print(name.upper())
print(name.lower())
print(name.swapcase())

Python
PYTHON
python
PyThOn


In [9]:
# make a string at center
name = "pYtHoN"
name.center(50)

'                      pYtHoN                      '

In [10]:
# to remove unwanted sapce
Name = '                      pYtHoN                      '
Name.strip()

'pYtHoN'

In [11]:
Name = '                      pYtHoN                      '# left strip left sapce remove
Name.lstrip()

'pYtHoN                      '

In [ ]:
name = '                      pYtHoN                      '
name.rstrip()

In [3]:
# count he number of given occurancve of sa given sub string using start and end
string = "annamalai is vip"
substring = "a"
count = string.count(substring)
print("the count is = ",count)

the count is =  4


In [ ]:
# count the range between 0 to 7
count = string.count(substring,0,7)
print("the count is = ",count)

In [12]:
# return true or false if the string contain alpha numeric

num = "annamalai08"
print(type(num))
print(num.isalnum())

num1 = "this is a string!!!"
num1.isalnum()

<class 'str'>
True


False

In [13]:
# return true or false if the string contain alphabet
num = "annamalai"
print(num.isalpha())

num = "annamalai08"
num.isalpha()

True


False

In [ ]:
# return true or false if the string contain digit
num = "12345"
print(num.isdigit())

num = "dhoni"
print(num.isdigit())


In [7]:
# the following examply show that replace()

reply = "it is a string example!! is really stringis paris is is is"
print(reply.replace("is", 'was'))
print(reply.replace("is", 'was', 3)) # first 3 it is replace

it was a string example!! was really stringwas parwas was was was
it was a string example!! was really stringwas paris is is is


In [8]:
# joining
print(":".join(reply))

i:t: :i:s: :a: :s:t:r:i:n:g: :e:x:a:m:p:l:e:!:!: :i:s: :r:e:a:l:l:y: :s:t:r:i:n:g:i:s: :p:a:r:i:s: :i:s: :i:s: :i:s


In [ ]:
#the following example shows that split()
split1 = "line1-abcdef \nline2-avfd \nline3dfwjhjwsj"
print(split1.split())
print(split1.split(" ", 1)) # 1 time split

In [5]:
x = "a-dspam_coincidence: 1.646834836"
y = x.find(":")
print(y)

num = float(x[y+1:])
print(num, type(num))

19
1.646834836 <class 'float'>


# tuple asssignment


In [ ]:
# multiple variable packeed in tuple can assigned in a single statement (ex;(a,b,c) = (10, 20, 30))
# variable and values should be same

In [ ]:
# swap the values of two variables
x = 2; y =3
print(x,y)

temp = x
x = y
y = temp
print(x,y)

In [ ]:
# tuple assignment solve the problem neatly

x = 2; y =3
print(x,y)

(x, y) = (y, x)
print(x, y)

In [ ]:
# circulate the values of n variable

#ex= n = 1 thrn re-arrange the number starting index as "1". index 0 will move at the end
#ex= n = 2 thrn re-arrange the number starting index as "2". index 0 and 1 will move at the end

In [2]:
a = list (input("enter the list = "))
print(a)

len(a)



enter the list = 12345
['1', '2', '3', '4', '5']


5

In [3]:
# arrange the order based on the numbers

for i in range(1, len(a), 1):
    print(a[i:] + a[:i]) # shift location

['2', '3', '4', '5', '1']
['3', '4', '5', '1', '2']
['4', '5', '1', '2', '3']
['5', '1', '2', '3', '4']


In [ ]:
for i in range (2, 30, 3):
    print(i)

# distance betwwn two points


In [ ]:
# distance between two points otherwise called as eucledian distance
# distance can never been negative
# distance between the same point is zero
# distance between i to j = j to i
# distance between the two sides is greater than or equal to one side in traingle

In [ ]:
# library- collection of code - programmer are done in past and we can reuse

In [ ]:
import math # library

x1 = int(input("enter the x1 = "))
y1 = int(input("enter the y1 = "))

print(x1,y1)

In [ ]:
x2 = int(input("enter the x2 = "))
y2 = int(input("enter the y2 = "))

print(x2, y2)

In [ ]:
# distance between the two points in xy plain
# euclidean distance method

distance = math.sqrt(((x2 - x1)**2) + ((y2 - y1)**2))
print(distance)

# conditional statement

In [ ]:
# if condition

a = 29

if a >= 22:
    print("if")
    

In [ ]:
x = 2

if x < 5:
    print(x)
print(5)    

In [ ]:
x = 2
y = 25
print(x)

if x < y:
    print(x)
print(y)    

In [4]:
# if and else condition

is_male = False

if is_male: # true
    print("you are male")
else: # false
    print("you are female")

you are female


In [ ]:
is_male = True

if is_male:
    print("you are male")
else:
    print("you are female")

In [ ]:
a = 24

if a >= 22:
    print("if")
    print("once again")
elif a >= 21:
    print('elif')
else:
    print('else')

In [ ]:
is_male = False
is_tall = False

if is_male and is_tall:
    print("you are tall male")
elif is_male and not(is_tall):
    print("you are short male")
elif not(is_male) and is_tall:
    print("you are not male")
else:
    print("you are not male and not tall")

In [ ]:
# nested if - condition inside a conditional statement

score = 500
money = 6000
age = 55

if score > 100:
    print('you got good points')
    if money >= 5000:
        print('you win')
        if age >= 30:
            print("you are older age")
        else:
            print("you are young age")
    else:
        print("you lose")
else:
    print('you got bad points')

In [ ]:
# testing for an element in the list

list = ['annamalai', "gopi", 'bakiya', 'usha']

if 'bakiya' in list:
    print('found bakiya')
    
if "usha"  not in list:
    print("usha not found")

# loops

we use loops because of we need instruction multiple times then we need to repeat the code again and again with the help of loop we can perform in fewer lines.

ex: "hello world" print 1000 times then we neeed to write print 1000 times by using loop we can easily do few lines.
 
 types of loop: for, while, nested
 
 statement: continus,break, pass
 
 for: repeat the set of instruction until condition is false.it check condition before executing the body of the loop
 while: execute the set of instruction until the condition is satisfied
 nested: use loop inside the 'for' or 'while' loop
 
 continue: continue specific part of loop till the condition is true and leave the remaining part of the loop
 break: break the loop when the condition is met
 pass: when we don't want to run the condition, we use pass statement

In [ ]:
# for loop
# we use "for" keyword with the variable range,or pre_defined data types(list,set,dict,tuple,string) the looops end with colan



In [ ]:
# example for for loop

snacks = ["pizza", "kalan", 'burger', 'samosa', "bajji"]

for snack in snacks:
    print("current snacks : ", snack)
print("good day")    

In [ ]:
for i in range(1,23):
    print(i)

In [15]:
# range function will not return values

numbers = range(10)
print(numbers)

range(0, 10)


In [ ]:
a = list(range(0, 12))    # type error;list object is not callable
a 

In [ ]:
range(1, 5, 1)

In [ ]:
# range function using loop

for i in range(1, 10, 2):
    print(i)

In [ ]:
for i in range(1,10):
    print("20 hours class of day ", i)

In [ ]:
# return the even numbers without applying any condition

for i in range(0,20,2):
    print("the even number is ", i)


In [ ]:
#Traversing list

numbers = [2, 3, 5]
sum = 0

for num in numbers:
    sum += num # sum = sum + num
print(sum)    

In [5]:
numbers = [2, 3, 5]

getsum = [i + 2 for i in numbers]
print(getsum)

for i in numbers:
    getsum = i + 2
    print(getsum)    
    
    

[4, 5, 7]
4
5
7


In [ ]:
numbers = [2, 3, 5]

getsum = [i +2 for i in numbers if i < 5]
print(getsum)

for i in numbers:
    getsum = i + 2
    if i < 5:
        print(getsum) 

In [7]:
# Nested 'for loop'
# factorial

num = int(input("enter the number = "))
factorial = 1

if num < 0:
    print("must be positive")
elif num == 0:
    print("factorial is 0")
else:
    for i in range(1, num + 1):
        factorial = factorial * i
        print(factorial)   


enter the number = 5
1
2
6
24
120


In [ ]:
list = [24, 56, 78, 97,31]

for i in list:
    if i % 2 == 0:
        print(i,"even number")
    else:
        print(i, "odd number")

In [8]:
num = int(input("enter the number = "))
factorial = 1

for i in range(1, num + 1):
    factorial = factorial * i
print(factorial) 

enter the number = 5
120


In [ ]:
list = [ 34, 45, 56, 78, 99, 999]
sum = 0

for i in list:
    sum += i
print(sum)

In [10]:
# pass statement

names = ['annamalai', 'amma', 'dad', 'anna', 'akka']

for i in names:
    pass
        

In [11]:
# continue

for i in names:
    if len(i) == 3:
        continue
    print("my name is ", i)
    
for i in names:
    if len(i) == 3:
        print(i)
    

my name is  annamalai
my name is  amma
my name is  anna
my name is  akka
dad


In [ ]:
for i in names:
    if len(i) == 3:
        break
    print("name = ", i)    

In [ ]:
for i in range(1, 10):
    if i == 5:
        break
    print(i)
print('done')    

In [37]:
n = 7
k = n + 1

for i in range(0, n):
    for j in range(0, k):
        print(" ", end = "")
    k = k - 1
    for j in range(0, i+1):
        print("* ", end = "")
    print("\r")    
        


        * 
       * * 
      * * * 
     * * * * 
    * * * * * 
   * * * * * * 
  * * * * * * * 


In [101]:
n = 7
k = n + 1

for i in range(0, n):
    for j in range(0, k):
        print(" ", end = "")
    print()
    k = k - 1

 * * * * * * * *
 * * * * * * *
 * * * * * *
 * * * * *
 * * * *
 * * *
 * *


In [ ]:
# for else

# if the else statement is used for loop, the else block is executed only if "for" loop terminates normally

In [ ]:
numbers = [11, 33, 55, 67, 97,43, 31, 39, 89, 21]

for num in numbers:
    if num % 2 == 0:
        print("the list contain even number")
        break
else:
    print("the list does not contain even mumber")

In [12]:
# enumerating the object of the list with sequential num

names = ['annamalai', 'amma', 'dad', 'anna', 'akka']

print(list(enumerate(names)))
enumerate(names)

[(0, 'annamalai'), (1, 'amma'), (2, 'dad'), (3, 'anna'), (4, 'akka')]


In [ ]:
for i,j in enumerate(names):
    print('index is {0} and value of index {1}'.format(i,j))

In [ ]:
# while loop

# the loop is used to iterate over a block code as long as the test expression

i = 0

while i < 10:
    print("the number is ", i)
    i = i + 1
    
    
    

In [ ]:
i = 0
while i < 10:
    pass
    i = i + 1

In [ ]:
i = 0
while i < 10:
    i = i  + 1
    if i == 5:
        continue
    print("the number is ", i)    

In [ ]:
i = 0
while i < 10:
    i = i  + 1
    if i == 5:
        break
    print("the number is ", i) 

In [ ]:
i = 0
while i < 10:
    print("number is", i)
    i = i + 1
else:
    print("the loop end")

In [36]:
# nested loop: we can use loop inside the loopo or than one times

list = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list, '\n')

for i in list:
    for j in i:
        print(f'square of {j} is', j ** 2)
    print('\n')    
        

[[1, 2, 3, 4], [5, 6, 7, 8]] 

square of 1 is 1
square of 2 is 4
square of 3 is 9
square of 4 is 16


square of 5 is 25
square of 6 is 36
square of 7 is 49
square of 8 is 64




In [ ]:
# define function

# imagine ther e are 1000 of codes created based on the requirements without using function
# if the reuirement repeated in the same code we can use function

print("hello world")
print("hello world")
print("hello world")
print("hello world")

def hello():
    print("hello worst world")
    
hello()   



In [ ]:
# not defined any value but just defined function

def hello_fun():
    pass

In [18]:
def sayhello(name, age, salary):
    print("my name is ", name, "my age is ", age, "my salry around ", salary)

sayhello("annamalai",24,220000)    


my name is  annamalai my age is  24 my salry around  220000


In [ ]:
# formal and actual arguments

# fun definition
def add(a,b):
    return a * b
add(3,4) # fun call

In [ ]:
# positional arguments

def rectangular_area(length,breadth):
    return length * breadth
rectangular_area(length = 3, breadth = 6)

In [ ]:
def print_max(a,b):
    if a > b:
        print(a, 'is maximum')
    elif a ==b:
        print(a, "equal to", b)
    else:
        print(b, 'is maximum')
        
print_max(3,8)        

In [ ]:
def say(message, times=1):
    print(message * times)
    
say("hello")
say('hello',5)


In [13]:
def func(a , b = 5, c = 8):
    print('a is', a, 'b is', b, "c is", c)
func(78,89)
func(b=100, a=65)
func(23, c=98)

a is 78 b is 89 c is 8
a is 65 b is 100 c is 8
a is 23 b is 5 c is 98


In [8]:
x = 50

def fun(x):
    print('x is', x)
    x = 2
    print('change local x to', x)
print('x is still', x)

fun(x)

x is still 50
x is 50
change local x to 2


In [14]:
# VARIABLE ARGUMENTS
# *ARGS foe variable number of arguments

def myfun(*argu):
    for arg in argu:
        print(arg)
        
myfun('hello', 'welcome', 'to', 'my room')        

hello
welcome
to
my room


In [ ]:
# using **kwargs to pass the variable keyword arguments to the function

def intro(**data):
    print("\ndata type of arguments :", type(data))
    
    for key, value in data.items():
        print('{} is {}'.format(key,value))
    
intro(first_name = "annamalai", age = 24, status = "vip")    



In [ ]:
def tot(initial, *numbers, **keywords):
    count = initial
    for number in numbers:
        count += number
    for key in keywords:
        count += keywords[key]
    return count

print(tot(10, 12, 13, 14, vegetables = 50, fruits = 10))

In [15]:
rows = int(input('enter the number = '))
column = int(input('enter the number = '))
symbol = input('enter the symbol = ')

for i in range(1, rows):
    for j in range(1, column):
        print(symbol, end = "")
    print("")    

enter the number = 5
enter the number = 4
enter the symbol = +
+++
+++
+++
+++


In [9]:
# fun call stack
# locals(), global()

x = 5 # global variable

def new():
    print('number is', x)
print(x)    

new()    

5
number is 5


In [13]:
x = 10
def new():
    x = 1 # local variable
    print("the number is", x)
    
print(x) 

new()

10
the number is 1


In [19]:
age = 24
name = "annamalai"
place = ["chennai", "kundrathur", "redhills"] # this are global variable

def local():
    age = 25 
    name = "dhoni" # this are local variable
    print("%s is %i years and lives in %s." % (name,age,place[0]))
    return
    
print("%%%%%%%%")
print("%s is %i years and lives in %s." % (name,age,place[1]))

local()

%%%%%%%%
annamalai is 24 years and lives in kundrathur.
dhoni is 25 years and lives in chennai.


In [21]:
print("* "* 8)

* * * * * * * * 


In [80]:
row = 5

for i in range(5):
    for j in range(i + 1):
        print("*", end = ' ')
    print()    
    

* 
* * 
* * * 
* * * * 
* * * * * 


In [98]:
row = 3

for i in range(row):
    for j in range(5):
        print('*', end = ' ')
    print()
        

* * * * * 
* * * * * 
* * * * * 


In [92]:
a = 3
print(a * 9, end = ' ')
print()

27 


In [29]:
# decline global variable with in the function

x = 8

def new():
    global x
    x = 9
    print('number is', x)
    
new()
print(x)

number is 9
9


In [32]:
# recursion (using conditions and loops)
# without recursion declaring the function

def fact(n):
    if n < 0:
        print('number should be positive')
    elif n == 0:
        print(f"factorial of {n}! is {1}")
    else:
        fact = 1
        for i in range(1, n+1):
            fact *= i
        print(f"factorial of {n}! is {fact}")  
        
fact(6)        

factorial of 6! is 720


In [34]:
def fact(n):
    if n < 0:
        print('number should be positive')
    elif n == 0:
        print(f"factorial of {n}! is {1}")
    elif n == 1:
        return 1
    else:
        return (n * fact(n-1))
fact(6)    

720

In [39]:
new_list = [i for i in range(12) if i % 2 == 1]
print(new_list)

[1, 3, 5, 7, 9, 11]


In [1]:
# list comprehension and readability (comprehension means single line of code)

# built a list of unicode codepoints from string in a ordinary way

symbols = '$¤£¥¢'
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

codes


[36, 164, 163, 165, 162]

In [12]:
# alternative way to perform the above unicode using list comprehension

codes = [ord(symbol) for symbol in symbols]
codes.sort()
codes.reverse()
codes

[165, 164, 163, 162, 36]

In [3]:
# dictionery comprehension

numbers = range(10)
print(numbers)

new_dict = {}

for n in numbers:
    if n % 2 == 0:
        new_dict[n] = n ** 2
    
print(new_dict)    

range(0, 10)
{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


In [7]:
dictionery = {n: n**2 for n in numbers if n % 2 == 0}

print(dictionery)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


In [14]:
dict1 = {'a': 1, 'b': 2, 'c' : 3, 'd' : 4, 'e' : 5}
dict1_keys = {k*2 : v*2 for (k,v) in dict1.items()}
print(dict1_keys)

{'aa': 2, 'bb': 4, 'cc': 6, 'dd': 8, 'ee': 10}


In [16]:
# zip and unzip

name = ['annamalai', 'gopi', 'nilani', 'sri']
roll_no = [ 3, 4, 1, 2]
marks = [ 70, 90, 100, 99]

mapped = zip(name,roll_no,marks) # using zip to map values

mapped = set(mapped) # converting values to print as set

print("the zipped result is ")
print(mapped)

the zipped result is 
{('annamalai', 3, 70), ('nilani', 1, 100), ('sri', 2, 99), ('gopi', 4, 90)}


In [17]:
unzip = zip(*mapped)

unzip = list(unzip)

print(unzip)

[('annamalai', 'nilani', 'sri', 'gopi'), (3, 1, 2, 4), (70, 100, 99, 90)]


In [25]:
namz, roll_noz , marksz = zip(*mapped)

print("the unzipped result is : \n", end = "")
print("the name list is : ", end = '')
print(namz)
print("the roll_noz list is : ", end = '')
print(roll_noz)
print("the markz list is : ", end = '')
print(marksz)

the unzipped result is : 
the name list is : ('annamalai', 'nilani', 'sri', 'gopi')
the roll_noz list is : (3, 1, 2, 4)
the markz list is : (70, 100, 99, 90)


In [35]:
a = 'annamalai'
b = 'nilani'

print(a)
"\n"
print(b)

annamalai
nilani


In [38]:
# built in sort function

animals = ['dog', 'elephant', 'cat', 'zebra', 'monkey', 'snake', 'cockroach']
sorted(animals)

['cat', 'cockroach', 'dog', 'elephant', 'monkey', 'snake', 'zebra']

In [47]:
# descending
sorted(animals, reverse = True)

['zebra', 'snake', 'monkey', 'elephant', 'dog', 'cockroach', 'cat']

In [48]:
#ascending order with respect to character
sorted(animals, key = len)

['cat', 'dog', 'snake', 'zebra', 'monkey', 'elephant', 'cockroach']

In [49]:
# descending ordwe with respect to character
sorted(animals, key = len, reverse = True) # if the len is same it comes to left to right

['cockroach', 'elephant', 'monkey', 'snake', 'zebra', 'cat', 'dog']

In [50]:
# built in function

animals.sort()
animals

['cat', 'cockroach', 'dog', 'elephant', 'monkey', 'snake', 'zebra']

# augumented assignment with sequence


In [55]:
l = [1, 2, 3]

print(id(l), l)

# ID of list will not change just append the values in the same id(list is mutable)

l *= 2
print(id(l), l)

2227391760576 [1, 2, 3]
2227391760576 [1, 2, 3, 1, 2, 3]


In [58]:
t = (1,2,3)
print(id(t), t)

t *= 2 # it can't replace create a new value or location(it is immutable)
print(id(t), t)

2227390747968 (1, 2, 3)
2227391999008 (1, 2, 3, 1, 2, 3)


In [59]:
# list is mutable - same memory location is getting updated
# set is immutable - creating diffferent memory location

# Handling missing values

In [61]:
d = {'a' : 1, 'b' : 2}

print(d['c'])

KeyError: 'c'

In [24]:
d = {'a' : 1, 'b' : 2}
print(d['a'])

try:
    print(d['c'])
    
except:KeyError
print("there is no error")

1
there is no error


In [67]:
# we can handle these kind of errors
# importing collect for default dictionery, collection is a library
# lambda = nameless function

import collections as cl

defd = cl.defaultdict(lambda : 'key not available')

defd['a'] = 1
defd['b'] = 2


print('the values of a is ', end = '')
print(defd['a'])

print('the values of c is ', end = '')
print(defd['c'])


the values of a is 1
the values of c is key not available


In [8]:
# lambda function

s = lambda x : x * x
s(12)

144

In [9]:
# map function

val = [1, 2, 3, 4, 5]

list(map(lambda x: x*2, val)) # filter(function,iterable)

[2, 4, 6, 8, 10]

In [10]:
list(map(str,val))

['1', '2', '3', '4', '5']

In [13]:
# filter function (function return true false)

list(filter(lambda x : x%2 == 0, val))

[2, 4]

In [15]:
list(filter(lambda x : x < 50, range(1,100)))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [24]:
# reduce fumnction

from functools import reduce

val = [1, 2, 3, 4, 5, 6]

reduce(lambda x,y : x * y, val)

720

In [25]:
import functools

lis = range(1,100)

sum = functools.reduce(lambda x,y : x + y, lis)
print(sum)

4950


In [27]:
help(reduce)

Help on built-in function reduce in module _functools:

reduce(...)
    reduce(function, iterable[, initial]) -> value
    
    Apply a function of two arguments cumulatively to the items of a sequence
    or iterable, from left to right, so as to reduce the iterable to a single
    value.  For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
    ((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
    of the iterable in the calculation, and serves as a default when the
    iterable is empty.



In [45]:
 # loop vs comprehension vs map
    
list1 = [1, 2, 3, 4, 5]
square1 = []

for i in list1:
    square1.append(i**2)
    
square2 = [i ** 2 for i in list1]

square3 = list(map(lambda x : x**2, list1))

square1, square2, square3
    


([1, 4, 9, 16, 25], [1, 4, 9, 16, 25], [1, 4, 9, 16, 25])

In [48]:
# iterators is the process run again and again (use __iter__, __next__)
# iterator is an object which programmertraverse through all the elements of collection regardless, specfic function

names = ["annamalai", 'gopi', 'nilani', 'sri']
print(names)

my_list = names.__iter__()
print(my_list)

['annamalai', 'gopi', 'nilani', 'sri']


In [50]:
help(iter)

Help on built-in function iter in module builtins:

iter(...)
    iter(iterable) -> iterator
    iter(callable, sentinel) -> iterator
    
    Get an iterator from an object.  In the first form, the argument must
    supply its own iterator, or be a sequence.
    In the second form, the callable is called until it returns the sentinel.



In [51]:
for i in names:
    print(i)

annamalai
gopi
nilani
sri


In [57]:
# another way of converting iterator
names = ["annamalai", 'gopi', 'nilani', 'sri']
my_list= iter(names)

print(next(my_list))


annamalai


In [58]:
print(next(my_list))
print(next(my_list))

gopi
nilani


In [59]:
names = range(1,150)
for obj in names:
    print(obj)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149


In [62]:
new_list = iter(names)
for obj in new_list:
    print(obj)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149


In [65]:
import sys
print(f'size of the variable names is {sys.getsizeof(names)}bytes')
print(f'size of the variable names is {sys.getsizeof(new_list)}bytes')

size of the variable names is 48bytes
size of the variable names is 32bytes


In [73]:
iterable_name = 'machine learning'
iterable_obj = iter(iterable_name)

while True:
    try:
        items= next(iterable_obj)
        print(items)
    except stopiteration:
        break
        

m
a
c
h
i
n
e
 
l
e
a
r
n
i
n
g


NameError: name 'stopiteration' is not defined

# generator

generator are built in function in python. generates sequence of value over time.
it consumes less space and memory.
it gives the iterate of value.


In [1]:
def generator(token_count):
    for i in range(token_count):
        yield i   

In [2]:
a = generator(10)
print(a)

<generator object generator at 0x000001B13B9929D0>


In [3]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [4]:
def sequence(n):
    x=[]
    for i in range(n):
        x.append(i)
    return x    

In [5]:
alist = sequence(50)
print(alist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [6]:
def sequence(n):
    for i in range(n):
        yield i

In [7]:
blist = sequence(50)
print(blist)

<generator object sequence at 0x000001B13B993060>


In [8]:
import sys
print(f'size of the variable names is {sys.getsizeof(alist)}bytes')
print(f'size of the variable names is {sys.getsizeof(blist)}bytes')

size of the variable names is 472bytes
size of the variable names is 104bytes


In [9]:
def fib(limit):
    a, b = 0, 1
    while a < limit:
        yield a
        a, b = b, a+b
        
x = fib(5)    # creating the generating object    

In [11]:
# iterating over generator object using next

while True:
    try:
        print(next(x), end = '\n')
    except stopiteration:
        break
    

0
1
1
2
3


NameError: name 'stopiteration' is not defined

# FILE HANDLING


In [1]:
# the open function has two parameters - filename and mode #
# there are 4 methods for opening file
# 'r'- read the dwefault value
# 'a'- open the file for append and craete a file does not exist
# 'w'- write open a file for writing
# 'x'- create a file

# syntax- variable = open(filename,mode)
# variable.close()

In [2]:
import os
print(os.getcwd())

C:\Users\annam


In [21]:
file = open('demo_file.txt')
print(file)
print(file.read())

<_io.TextIOWrapper name='demo_file.txt' mode='r' encoding='cp1252'>
Hello! welcome to python programming
this file is testing purpose
good luck!


In [9]:
# another way to open a file

with open('demo_file.txt') as file:
    x = file.read()

In [10]:
x

'Hello! welcome to python programming\nthis file is testing purpose\ngood luck!'

In [11]:
f = open('demo_file.txt')
f.readline()

'Hello! welcome to python programming\n'

In [17]:
f = open('demo_file.txt', mode = 'r')
f.readlines()

['Hello! welcome to python programming\n',
 'this file is testing purpose\n',
 'good luck!']

In [20]:
f = open('demo_file.txt', 'r')
f.read()

'Hello! welcome to python programming\nthis file is testing purpose\ngood luck!'

In [23]:
f = open('demo_file.txt', 'r')
f.read(9)

'Hello! we'

In [25]:
# write to an existing file
f = open('demo_file.txt', 'a') # create or append
f.write("now the file has more content")
f.close()

In [27]:
f = open('demo_file.txt', 'r')
f.read()

'Hello! welcome to python programming\nthis file is testing purpose\ngood luck!now the file has more contentnow the file has more content'

In [28]:
# creating a new file

f = open('demo2_file.txt', 'x') # create
f.write('new file')
f.close()

In [29]:
f = open('demo2_file.txt', 'r')
f.read()

'new file'

In [34]:
# deleting a file
import os
os.remove('winzip')

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'winzip'

# exception handling



In [36]:
# try and except are keywords for exceptional handling , try - provide the code ; except- except the error with proper statement

try:
    x = eval(input('enter the number1 = '))
    y = eval(input('enter the number2 = '))
    z = x+y
    print(z)
except:
    print('please enter valid number')
    

enter the number1 = 1
enter the number2 = a
please enter valid number


In [38]:
x = eval(input('enter the number1 = '))

enter the number1 = abc


NameError: name 'abc' is not defined

In [44]:
try:
    x = eval(input('enter the number1 = '))
    y = eval(input('enter the number2 = '))
    z = x/y
    print(z)
except(ZeroDivisionError): # divide by zero
    print("please enter a non zero value for a division")
except(NameError): # use interger
    print("please enter valid number")
except(TypeError): # use (integer or string)
    print("please enter both are same type")
    
    

enter the number1 = 1
enter the number2 = 'a'
please enter both are same type


In [45]:
6/0

ZeroDivisionError: division by zero

In [46]:
5/a

NameError: name 'a' is not defined

In [47]:
5/'a'

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [51]:
# in python,keywords and else and finally, can be used along with try and except clause.while the except block is executed
# if the exception occurs inside the "try" block, the 'else' block get proceed if the 'try' block is found to be exception free

try:
    x = int(input('enter the number1 = '))
    y = int(input('enter the number2 = '))
    z = x/y
    print(z)
except(ZeroDivisionError): # divide by zero
    print("except zerodivision error block")
    print("division by zero not accepted")
else:
    print("else block")
    print('division = ', z)
finally:
    print('finally block')
    x = 0
    y = 0
print("out of try,except,else and finally blocks.") 


enter the number1 = 1
enter the number2 = 2.0
finally block


ValueError: invalid literal for int() with base 10: '2.0'

# built in exceptions


In [52]:
# there are plenty of built-in-exceptions in python that are raised corresponding error occur:
# we can view all the built-in exceptions using built in local() functions as allows

print(dir(locals()['__builtins__']))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EncodingWarning', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWar

In [54]:
# user defined function
x = int(input('enter the number = '))
if x < 18:
    raise Exception('sorry, you are not eligible for voting , register once you became 18 years old')
else:
    print("you entered = ", x)

enter the number = 23
you entered =  23


# class and objects


In [10]:
# In class there is an multiple object in a class and multiple function
# x = 10 here x is an object

class bike:
    
    def __init__(self, mpg, speed, length, b):
        self.mpg = mpg
        self.speed = speed
        self.length = length
        self.b = b
    
    def get_mpg(self):
        print(self.mpg)
        
    def area(self):
        print(self.length*self.b)
        
    def config(self):
        print("1000cc, abs")
        
    def speed(self):
        print("top speed is 250")
        
comp1 = bike(55, 200, 2, 8)   # once we create class we have to save in the cojnstructor so comp1 is a constructor     

In [4]:
comp1.get_mpg()

55


In [12]:
comp1.config()

1000cc, abs


In [18]:
comp1.area()

16


# Inheritance


In [68]:
# inheritance is a power ful feature in object oriented programming.
# single level, multilevel, multiple inheritance
# inherit the properties of single class or multiple class

class A:
    def product1(self):
        print('print product name1: ')
        
    def product2(self):
        print('print product name2: ')
        

In [71]:
name_a = A()

print(id(name_a))
name_a.product1()

1428594951888
print product name1: 


In [3]:
# inheritance. A is a super class and b is a sub class

class B(A):
    def product3(self):
        print('print product name3: ')
        
    def product4(self):
        print('print product name4: ')    

In [4]:
name_b = B() # constructor

print(id(name_b))
name_b.product3() # function is sub class

2627708645776
print product name3: 


In [5]:
name_b.product2() # function is superclasss and accessed by sub class
# all of in A which inherited by B

print product name2: 


In [6]:
class C:
    
    def product5(self):
        print('print product name5: ')
        
    def product6(self):
        print('print product name6: ')    

In [7]:
name_c = C()

In [8]:
# multiple inheritance
class D(A, C):
    def product7(self):
        print('print product name7: ')
        
    def product8(self):
        print('print product name8: ')    

In [9]:
name_d = D()

name_d.product1()

print product name1: 


# polymorphism

In [72]:
# polymorphism means different ttpes of class and respond to the same functiom.polymorphism is very useful it makes
# programmimg more initiative and more easier

class Bird:
    def intro(self):
        print('there are many types of birds')
        
    def flight(self):
        print('most of the birds can fly and some cannot')
        
        

In [73]:
class sparrow(Bird):
    def flight(self):
        print('sparrow can fly')
        
class ostrich(Bird):
    def flight(self):
        print('ostrich cannot fly') # different calsses implementing same method

In [74]:
# creative instances of respective classes
obj_Bird = Bird()
obj_sparrow = sparrow()
obj_ostrich = ostrich()

In [75]:
obj_sparrow.flight()

sparrow can fly


In [32]:
obj_Bird.flight()

most of the birds can fly and some cannot


In [37]:
obj_ostrich.flight()

ostrich cannot fly


# multi-threading


In [25]:
# it's used for faster processing

import time

def calc_square(numbers):
    print("calculate the square numbers")
    for n in numbers:
        time.sleep(0.3) # next line of code executed in 0.3 sec
        print('square: ', n*n)
        
def calc_cube(numbers):
    print("calculate the cube numbers")
    for n in numbers:
        time.sleep(0.1)
        print('cube: ', n*n*n)        

In [26]:
arr = [2, 5, 7, 9]

t = time.time() # it's calculated 1st jan 1970 to current time in sec
print(t)

calc_square(arr)

1687328086.2708457
calculate the square numbers
square:  4
square:  25
square:  49
square:  81


In [27]:
calc_cube(arr)

calculate the cube numbers
cube:  8
cube:  125
cube:  343
cube:  729


In [28]:
print('done in: ', time.time()- t ) # currrent time - executed time
print("completed my work")

done in:  10.411209106445312
completed my work


In [29]:
# context switching- during the wait time lag it will execute another line of program

# in serial processsing it will executed line by line by time but in parallel processing it run at a time 

import threading

t1 = threading.Thread(target=calc_square, args=(arr, ))
t2 = threading.Thread(target=calc_cube, args=(arr, ))

t = time.time()

t1.start()
t2.start()

t1.join()
t2.join()

print('done in: ', time.time()- t ) # currrent time - executed time
print("completed my work")



calculate the square numberscalculate the cube numbers

cube:  8
cube:  125
square:  4
cube:  343
cube:  729
square:  25
square:  49
square:  81
done in:  1.3090105056762695
completed my work


# module

In [64]:
# module are also called as packages or libraries
# how to call package is : Import package_name

import math

print(math.sqrt(16))

math.pow(3,5)

4.0


243.0

In [65]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [71]:
import calendar

cal = calendar.month(2023, 6)
print(cal)

     June 2023
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30



In [72]:
print(calendar.isleap(2018))
print(calendar.isleap(2020))

False
True


# how to create a own module

In [1]:
# create a new python file 'find_area.py' with different function as given below

# def cal_area_triangle(length,height):
#    return 1/2*length*height

# def cal_area_sqr(length):
#    return length*length

# def cal_area_rec(length,breadth):
#    return length*breadth

# def cal_area_cir(r):
#    return 3.14*r*r

# end of the code

# importing function from another file

In [1]:
# give path for the module

import sys

sys.path.append('find_area.txt')

# sys.path

In [5]:
2+2

4

In [6]:
# import math

# from math import cos

# import math.cos

# import math as m

# from math import* or import math

In [7]:
# all() function when all entries are true return true otherwise false

s = {0 : False, 1 : True}
print(all(s))

s = {1 : True, 2 : True}
print(all(s))

s = {0 : False, 1 : True}
print(all(s))


False
True
False


# Regular expression

In [19]:
import re

txt = "The rain in Hydrabad"

x = re.search("^The.*Hydrabad$", txt)
if x:
    print("x is match")
    
else:
    print('not match')

x is match


In [10]:
import re

txt = "The rain in Hydrabad"

x = re.findall('ai', txt)

print(x)

['ai']


In [24]:
import re

nameage = '''Annamalai is 24 and Gopi is 27 and Bakiya is 29 and Nilani is 1 and Mom is 50 and Dad is 12345'''

age = re.findall(r'\d{1,3}', nameage ) # \ means string digit
names = re.findall(r'[A-Z][a-z]*',  nameage)

print(age)
print(names)

agedict = {}

x = 0

for eachname in names:
    agedict[eachname] = age[x]
    x += 1
    
print(agedict)    

['24', '27', '29', '1', '50', '123', '45']
['Annamalai', 'Gopi', 'Bakiya', 'Nilani', 'Mom', 'Dad']
{'Annamalai': '24', 'Gopi': '27', 'Bakiya': '29', 'Nilani': '1', 'Mom': '50', 'Dad': '123'}


In [29]:
import re

txt = "The rain in Hydrabad"

x = re.split('\s', txt)
print(x)

['The', 'rain', 'in', 'Hydrabad']


In [30]:
string = 'Twelve:12 Eighty one:81.'
pattern = '\d+'

print(re.split(pattern,string))

['Twelve:', ' Eighty one:', '.']


In [34]:
import re

phone = "249-939-9063 # This is phone number"

# deleting python style comments
num = re.sub(r'#.*$',"",phone)
print(num)

# delete other than digvits
num= re.sub('\D', '', phone)
print(num)



249-939-9063 
2499399063


In [36]:
import re

allname = re.findall('name', 'my name is annamalai and what is your name')
print(allname)

for name in allname:
    print(name)

['name', 'name']
name
name


In [11]:
import re

allname = "my name is annamalai and what is your name"

for i in re.finditer("name", allname):
    loctup = i.span() # return a tuple containing start and end position of the match
    print(loctup) # span - index location
    
    
    

(3, 7)
(38, 42)


In [38]:
import re

name = 'Aam, Bam, Sam, Mam, Yam, Lam'

allnames = re.findall('[A-M]am', name)
print(allnames)

for i in allnames:
    print(i)

['Aam', 'Bam', 'Mam', 'Lam']
Aam
Bam
Mam
Lam


In [3]:
# replace string
import re

names = "Sam Ram Dom kane"
regex = re.compile("[S]am")
x = regex.sub('sama', names)
print(x)

sama Ram Dom kane


In [1]:
# replace a first two occurance of space character with a digit 9

import re

txt = "The rain in Hydrabad"

x = re.sub('\s','9', txt, 2)
print(x)

The9rain9in Hydrabad


In [2]:
# dividing number, alpha, spec character

import re

re.sub('[A-Za-z]','*', 'ada1231xytes #$%&@zhga678')

'***1231***** #$%&@****678'

In [5]:
import re

re.sub('[^A-Za-z]','&', 'ada1231xytes #$%&@zhga678') # ^ - not

'ada&&&&xytes&&&&&&zhga&&&'

In [2]:
# remove white space

randstr = '''
my
name
is
annamalai
'''
print(randstr)

print(randstr, end=' ')


my
name
is
annamalai


my
name
is
annamalai
 

In [9]:
regex = re.compile('\n')

randstr = regex.sub(" ", randstr)
print(randstr)

mynameisannamalai


In [15]:
randstr = 'a12345'

print(len(re.findall('\d', randstr)))

print(re.search(r'\d{2}', randstr))

5
<re.Match object; span=(1, 3), match='12'>


In [16]:
# pan number verfication

# \d -[0-9]- digits
# \w - [a_zA-Z0-9] - alphanum

pan = '1234-5678-AA123476bagfN78'

if re.search('\d{4}-\d{4}-\w{15}', pan):
    print('it is a pan number')
    
else:
    print("not pan number")

it is a pan number


In [19]:
name = 'my name is annamalai and right now iam vip'

re.split(' ', name)

['my', 'name', 'is', 'annamalai', 'and', 'right', 'now', 'iam', 'vip']

In [21]:
string = 'python programming is very fun'

match = re.search('\Apython', string) # \A - return a match character beginning of the string

if match:                                 # \B - beginning or end
    print('pattern found inside the string')
    
else:
    print('not found')

pattern found inside the string


# Python packages of data analysis

# numpy


In [4]:
import numpy as np

x = [12, 34, 56, 98, 1, 5, 6]

# the list values into 2

x * 2

[12, 34, 56, 98, 1, 5, 6, 12, 34, 56, 98, 1, 5, 6]

In [7]:
# numpy array will help access the value

y = np.array(x)
print(y)
print(type(y))
print(y * 2)

[12 34 56 98  1  5  6]
<class 'numpy.ndarray'>
[ 24  68 112 196   2  10  12]


In [8]:
y > 10

array([ True,  True,  True,  True, False, False, False])

In [9]:
y[y > 10] # index of y it shows the true value

array([12, 34, 56, 98])

In [13]:
from numpy import random

x = random.randint(12, 78)
print(x)

20


In [19]:
# numpy array share the memory instead of allocate seperate memory
a = np.arange(10)
print(a)

b = a[::2]
print(b)

print(np.shares_memory(a, b)) # check wheather a nad b are share memory

a, b



[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 2, 4, 6, 8]))

In [24]:
arr = np.array([[1, 4, 5, 8, 9],[12, 13, 16, 18, 20]]) # index value 0 and 1
print(arr)

print(arr[0, 2])
print(arr[0, 0])
print(arr[1, 0])
print(arr[1, 3])

[[ 1  4  5  8  9]
 [12 13 16 18 20]]
5
1
12
18


In [27]:
arr = np.array([1, 4, 5, 8, 9, 12, 14, 16, 18])
arr[1:4]

array([4, 5, 8])

In [29]:
arr[1:7:2]

array([ 4,  8, 12])

# masking arrays

In [3]:
import numpy as  np
a = np.arange(10)

mask = (a % 2 == 0)
print(mask)
a[mask]

[ True False  True False  True False  True False  True False]


array([0, 2, 4, 6, 8])

In [35]:
a % 2 

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

# numpy matrix

In [38]:
# ex:1

a = np.matrix('1 2 ; 3 4')
print(a)

b = np.matrix([[1, 2],[3, 4]]) # ex;2
print(b)



[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [39]:
c = np.matrix('1 2 3 ; 3 4 5 ; 5 6 7')
print(c)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


# numpy broadcasting

In [12]:
# it works on different sized of array

import numpy as np

a = np.arange(0, 40, 10)
print(a)

b = np.array([1, 4, 15,])
print(b)

a.shape, a, b.shape, b

[ 0 10 20 30]
[ 1  4 15]


((4,), array([ 0, 10, 20, 30]), (3,), array([ 1,  4, 15]))

In [24]:
a= a[:, np.newaxis] # add one extra axis
a.shape

(4, 1, 1)

In [25]:
print(a)
print('*********')
print(b)
print('********')
a + b

[[[ 0]]

 [[10]]

 [[20]]

 [[30]]]
*********
[ 1  4 15]
********


array([[[ 1,  4, 15]],

       [[11, 14, 25]],

       [[21, 24, 35]],

       [[31, 34, 45]]])

# data structure
# arrays/vectors

In [33]:
# creating an array
# array is created in python by importing arraymodule to the python programmimg

from array import *

arr1 = array('i',[10, 20, 30, 40, 50])
print(arr1)

for x in arr1:
    print(x)

array('i', [10, 20, 30, 40, 50])
10
20
30
40
50


In [34]:
help(array)

Help on class array in module array:

class array(builtins.object)
 |  array(typecode [, initializer]) -> array
 |  
 |  Return a new array whose items are restricted by typecode, and
 |  initialized from the optional initializer value, which must be a list,
 |  string or iterable over elements of the appropriate type.
 |  
 |  Arrays represent basic values and behave very much like lists, except
 |  the type of objects stored in them is constrained. The type is specified
 |  at object creation time by using a type code, which is a single character.
 |  The following type codes are defined:
 |  
 |      Type code   C Type             Minimum size in bytes
 |      'b'         signed integer     1
 |      'B'         unsigned integer   1
 |      'u'         Unicode character  2 (see note)
 |      'h'         signed integer     2
 |      'H'         unsigned integer   2
 |      'i'         signed integer     2
 |      'I'         unsigned integer   2
 |      'l'         signed integer    

In [42]:
# insert option

from array import *

arr1 = array('i',[10, 20, 30, 40, 50])
arr1.insert(1, 60)


In [43]:
for x in arr1:
    print(x)

10
60
20
30
40
50


In [45]:
# delete
arr1.remove(40)

In [46]:
for x in arr1:
    print(x)

10
60
20
30
50


In [47]:
# update

arr1[2] = 80

for x in arr1:
    print(x)

10
60
80
30
50


# 2-D array

In [49]:
# the data elements in two dimensional array can be accessed by using idices
# one index refer to main or parent array another data element in inner array
# if we mentioned only one index then the entire inner array is printed for the index position

T = [[1, 2, 3, 4], [4, 7, 8, 9], [11, 23, 22], [45, 31, 18, 17]]

print(T[0])
print(T[1][2])

[1, 2, 3, 4]
8


In [50]:
# inserting values in two dimension array
T.insert(2, [12, 13, 15, 19])
T

[[1, 2, 3, 4], [4, 7, 8, 9], [12, 13, 15, 19], [11, 23, 22], [45, 31, 18, 17]]

In [53]:
# update values in two dimensional array

T[2] = [22, 26, 27, 28]
print(T)

T[1][3] = [90]
print(T)

[[1, 2, 3, 4], [4, 7, 8, [90]], [22, 26, 27, 28], [11, 23, 22], [45, 31, 18, 17]]
[[1, 2, 3, 4], [4, 7, 8, [90]], [22, 26, 27, 28], [11, 23, 22], [45, 31, 18, 17]]


In [54]:
# deleting values in two dimensional array

del T[3]
T

[[1, 2, 3, 4], [4, 7, 8, [90]], [22, 26, 27, 28], [45, 31, 18, 17]]

# matrix

matrix is a special case of two dimensional array where each data element are strictly same size . so evry matrix is also two dimensional array not vice versa, matrix important in data structure for mathematical and scientific operation

In [55]:
# matrix example

from numpy import *

a = array([["mon", 12, 23, 45, 56], ['tues', 89, 78, 56, 43], ['wed', 34, 56, 39, 30], ['thur', 56, 78, 90, 65], ['fri', 65, 78, 90, 87], ['sat', 32, 67, 98, 99], ['sun', 12, 34, 13, 16 ]])

c = reshape(a,(7, 5))
print(c)

[['mon' '12' '23' '45' '56']
 ['tues' '89' '78' '56' '43']
 ['wed' '34' '56' '39' '30']
 ['thur' '56' '78' '90' '65']
 ['fri' '65' '78' '90' '87']
 ['sat' '32' '67' '98' '99']
 ['sun' '12' '34' '13' '16']]


In [56]:
print(a[2])

['wed' '34' '56' '39' '30']


In [57]:
print(a[3][4])

65


In [61]:
# adding the data

m_r = append(a,[['avg', 11, 21, 31, 41]], 0) # add the row at the end (0--- row)

print(m_r)
print("********")

m_c = insert(a, [5], [[1], [2], [3], [4], [5], [6], [7]], 1) # add the insert by the location (1-- column)
print(m_c)

[['mon' '12' '23' '45' '56']
 ['tues' '89' '78' '56' '43']
 ['wed' '34' '56' '39' '30']
 ['thur' '56' '78' '90' '65']
 ['fri' '65' '78' '90' '87']
 ['sat' '32' '67' '98' '99']
 ['sun' '12' '34' '13' '16']
 ['avg' '11' '21' '31' '41']]
********
[['mon' '12' '23' '45' '56' '1']
 ['tues' '89' '78' '56' '43' '2']
 ['wed' '34' '56' '39' '30' '3']
 ['thur' '56' '78' '90' '65' '4']
 ['fri' '65' '78' '90' '87' '5']
 ['sat' '32' '67' '98' '99' '6']
 ['sun' '12' '34' '13' '16' '7']]


In [64]:
# delete

print(a)
print('$$$$$$')

n1 = delete(a, [2], 0) # row delete
print(n1)
print('******')

n2 = delete(a, [2], 1) # delete column
print(n2)

[['mon' '12' '23' '45' '56']
 ['tues' '89' '78' '56' '43']
 ['wed' '34' '56' '39' '30']
 ['thur' '56' '78' '90' '65']
 ['fri' '65' '78' '90' '87']
 ['sat' '32' '67' '98' '99']
 ['sun' '12' '34' '13' '16']]
$$$$$$
[['mon' '12' '23' '45' '56']
 ['tues' '89' '78' '56' '43']
 ['thur' '56' '78' '90' '65']
 ['fri' '65' '78' '90' '87']
 ['sat' '32' '67' '98' '99']
 ['sun' '12' '34' '13' '16']]
******
[['mon' '12' '45' '56']
 ['tues' '89' '56' '43']
 ['wed' '34' '39' '30']
 ['thur' '56' '90' '65']
 ['fri' '65' '90' '87']
 ['sat' '32' '98' '99']
 ['sun' '12' '13' '16']]


In [65]:
import numpy as np

np.arange(4)

array([0, 1, 2, 3])

In [66]:
z = np.diag(1 + np.arange(4))
print(z)
type(z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


numpy.ndarray

In [67]:
y = np.zeros(10)
y[4] = 2
print(y)

[0. 0. 0. 0. 2. 0. 0. 0. 0. 0.]


In [69]:
# create a random  veactor of size 30 and find the mean value

x = np.random.random(30)
print(x)

z = x.mean() # mean - add all the values
print(z)

[0.99551865 0.68388453 0.3041077  0.63048815 0.36210017 0.22391463
 0.93641673 0.42403901 0.54687924 0.50065669 0.69899384 0.43836937
 0.23944497 0.03285083 0.35947348 0.65789274 0.92404592 0.30153644
 0.55492511 0.63846188 0.49425772 0.67627461 0.06099071 0.69413669
 0.08348448 0.82188421 0.99532539 0.76410208 0.60445236 0.39326097]
0.5347389768200353


In [70]:
# revcerse a vector ( first became last)

v = np.arange(50)

v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# pandas

In [1]:
# importing necessary libraries

import pandas as pd # importing pandas as useful for creating data frames
import numpy as np  # useful for creating numpy arrays

 # pandas use of data manipulation crating rows and column, delete , given a name in the row
    
 # numpy use of numerical calculation   

In [2]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [5]:
x1 = [12, 13, 14, 15, 16]

x2 = [21, 22, 23, 24, 25]

x3 = list(range(5))

X = pd.DataFrame(columns = ["X1", "X2", "X3"]) # creating a dataframe using explicit list

print(X)

Empty DataFrame
Columns: [X1, X2, X3]
Index: []


In [8]:
X['X1'] = x1 # converting list format into pandas series format
X['X2'] = x2
X['X3'] = x3
X


X1  X2  X3
0  12  21   0
1  13  22   1
2  14  23   2
3  15  24   3
4  16  25   4

In [9]:
# copy same data into another variable

dff = X.copy(deep = False)# Shallow copy share data and index with orginal dataframe
print(dff)
dff1 = X.copy(deep = True) # deep copy has own copy of data and index
print(dff1)

   X1  X2  X3
0  12  21   0
1  13  22   1
2  14  23   2
3  15  24   3
4  16  25   4
   X1  X2  X3
0  12  21   0
1  13  22   1
2  14  23   2
3  15  24   3
4  16  25   4


In [11]:
# shallow copy

dff['X1'][0] = 10  
print(dff) # any cahange in tha shallow copy will make change in orginal data also

X

   X1  X2  X3
0  10  21   0
1  13  22   1
2  14  23   2
3  15  24   3
4  16  25   4


X1  X2  X3
0  10  21   0
1  13  22   1
2  14  23   2
3  15  24   3
4  16  25   4

In [12]:
# deep copy

dff1['X2'][1] = 99
print(dff1)  # in deep copy will not make changes in orginal data also

X

   X1  X2  X3
0  12  21   0
1  13  99   1
2  14  23   2
3  15  24   3
4  16  25   4


X1  X2  X3
0  10  21   0
1  13  22   1
2  14  23   2
3  15  24   3
4  16  25   4

In [14]:
# list into pandas data frame

X['X1'] = pd.Series(x1) # converting list format into pandas series format
X['X2'] = pd.Series(x2)
X['X3'] = pd.Series(x3)
print(X)
type(X)

   X1  X2  X3
0  12  21   0
1  13  22   1
2  14  23   2
3  15  24   3
4  16  25   4


pandas.core.frame.DataFrame

In [15]:
# accessing column using data operation

X.X1

0    12
1    13
2    14
3    15
4    16
Name: X1, dtype: int64

In [16]:
# access column alternative way
X['X1']

0    12
1    13
2    14
3    15
4    16
Name: X1, dtype: int64

In [17]:
# access multiple columns : giving column name as input in list format

X[['X1','X2']]

X1  X2
0  12  21
1  13  22
2  14  23
3  15  24
4  16  25

In [18]:
# accesing elements using index location 

print(X.columns)
print(X.iloc[0:3, 1]) # iloc- index loc ((0:3- rows, 1-colu))
X

Index(['X1', 'X2', 'X3'], dtype='object')
0    21
1    22
2    23
Name: X2, dtype: int64


X1  X2  X3
0  12  21   0
1  13  22   1
2  14  23   2
3  15  24   3
4  16  25   4

In [19]:
X.iloc[1:2, 1:2] # refer to 1st row and 1st column

X2
1  22

In [21]:
X.loc[0:2, ['X1', 'X2']] # mention specify column names

X1  X2
0  12  21
1  13  22
2  14  23

In [7]:
# merge operation using pandas data frame

import pandas as pd

df1 =  pd.DataFrame({'X1':[1, 2, 3,], 'X2':[4, 8, 12]})
print(df1)
df2 =  pd.DataFrame({'X1':[1, 2, 3, 4], 'X3':[4, 8, 12, 15]})
print(df2)

dfm= pd.merge(df1, df2, on = 'X1') # in merge we need same one  column name same otherwise error
print(dfm)

   X1  X2
0   1   4
1   2   8
2   3  12
   X1  X3
0   1   4
1   2   8
2   3  12
3   4  15
   X1  X2  X3
0   1   4   4
1   2   8   8
2   3  12  12


In [27]:
# joined operation

df1 =  pd.DataFrame({'X1':[1, 2, 3], 'X2':[4, 8, 12],}, index = [2000, 2001, 2002])
df2 =  pd.DataFrame({'X3':[1, 2, 3], 'X4':[4, 8, 12],}, index = [2001, 2002, 2003])

print(df1)
print('******')
print(df2)
print('******')

joined = df2.join(df1) # join function based on index value
print(joined)

      X1  X2
2000   1   4
2001   2   8
2002   3  12
******
      X3  X4
2001   1   4
2002   2   8
2003   3  12
******
      X3  X4   X1    X2
2001   1   4  2.0   8.0
2002   2   8  3.0  12.0
2003   3  12  NaN   NaN


In [29]:
df1 =  pd.DataFrame({'X1':[1, 2, 3], 'X2':[4, 8, 12],})
df2 =  pd.DataFrame({'X3':[1, 2, 3, 4], 'X4':[4, 8, 12, 5],})

print(df1)
print('******')
print(df2)
print('******')

joined = df1.join(df2) # join function based on index value
print(joined)

   X1  X2
0   1   4
1   2   8
2   3  12
******
   X3  X4
0   1   4
1   2   8
2   3  12
3   4   5
******
   X1  X2  X3  X4
0   1   4   1   4
1   2   8   2   8
2   3  12   3  12


In [31]:
# replace index name

df1 =  pd.DataFrame({'X1':[1, 2, 4], 'X2':[4, 8, 12],})
print(df1)
print('****')

df1.set_index('X1', inplace = True) # in  the place of index we got X1 value
print(df1)



   X1  X2
0   1   4
1   2   8
2   4  12
****
    X2
X1    
1    4
2    8
4   12


In [33]:
# change the column names

df1 =  pd.DataFrame({'X1':[1, 2, 4], 'X2':[4, 8, 12],})
print(df1)
print('****')

df = df1.rename(columns = {"X1": "X3"}) # X1 column name change as X3
print(df)



   X1  X2
0   1   4
1   2   8
2   4  12
****
   X3  X2
0   1   4
1   2   8
2   4  12


In [36]:
# concatination

df1 =  pd.DataFrame({'X1':[1, 2, 3], 'X2':[4, 8, 12],}, index = [2000, 2001, 2002])
df2 =  pd.DataFrame({'X3':[11, 12, 13, 15], 'X4':[14, 18, 22, 67],}, index = [2003, 2004, 2005, 2006])

print(df1)
print(df2)

concatinate = pd.concat([df2, df1])
print(concatinate)

      X1  X2
2000   1   4
2001   2   8
2002   3  12
      X3  X4
2003  11  14
2004  12  18
2005  13  22
2006  15  67
        X3    X4   X1    X2
2003  11.0  14.0  NaN   NaN
2004  12.0  18.0  NaN   NaN
2005  13.0  22.0  NaN   NaN
2006  15.0  67.0  NaN   NaN
2000   NaN   NaN  1.0   4.0
2001   NaN   NaN  2.0   8.0
2002   NaN   NaN  3.0  12.0


In [40]:
# dictionery to dataframe

data_set = {
    'cars': ['BMW', 'shift', 'honda'],
    'passenger': [7, 5, 6]
}

myvar = pd.DataFrame(data_set)
print(myvar)

    cars  passenger
0    BMW          7
1  shift          5
2  honda          6


In [6]:
# import data (.csv file) using pandas 

import pandas as pd

education = pd.read_csv("education.txt")
print(type(education))
education.shape

<class 'pandas.core.frame.DataFrame'>


(14, 1)

In [8]:
education.head(2) # it shows first 5 rows


Student ID | Student Name   | Gender | Date of Birth | Grade Level | School ID | School Name        | School Address        | City        | State       | Country       | Parent/Guardian Name   | Contact Number    | Email                         | Course Name         | Course Grade | Attendance Percentage | Extracurricular Activities        | Teacher Name  | Teacher ID | Teacher Email
001        | John Smith     | Male   | 2005-08-...   Debate Club           | Mr. Johnson   | 5001 ...                                                                                                                                                                                                                                                                                                                                                
002        | Emily Davis    | Female | 2006-03-...   Drama Club                | Mrs. Adams    | 5...

In [9]:
education.tail(1) # it shows bottom 5

Student ID | Student Name   | Gender | Date of Birth | Grade Level | School ID | School Name        | School Address        | City        | State       | Country       | Parent/Guardian Name   | Contact Number    | Email                         | Course Name         | Course Grade | Attendance Percentage | Extracurricular Activities        | Teacher Name  | Teacher ID | Teacher Email
014        | Amelia Martin  | Female | 2007-09-...                                                NaN

In [10]:
education.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 001        | John Smith     | Male   | 2005-08-15    | 9th grade   | 1001      | ABC High School    | 123 Main Street       | Anytown     | California  | United States | Jane Smith              | +1 123-456-7890  | john.smith@example.com        | Mathematics         | A            | 95%                   | Basketball to 014        | Amelia Martin  | Female | 2007-09-03    | 8th grade   | 1002      | XYZ Middle School  | 456 Oak Avenue        | Smallville  |
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                              Non-Null Count  Dtype 
---  ------                      

In [15]:
education.iloc(1)

In [16]:
education.describe()

Student ID | Student Name   | Gender | Date of Birth | Grade Level | School ID | School Name        | School Address        | City        | State       | Country       | Parent/Guardian Name   | Contact Number    | Email                         | Course Name         | Course Grade | Attendance Percentage | Extracurricular Activities        | Teacher Name  | Teacher ID | Teacher Email
count                                                  13                                                                                                                                                                                                                                                                                                                                                
unique                                                 13                                                                                                                                                                                                                                                                                                                                                
top      Debate Club           | Mr. Johnson   | 5001 ...                                                                                                                                                                                                                                                                                                                                                
freq                                                    1

In [17]:
help(pd)

C:\Users\annam\AppData\Local\anaconda3\lib\inspect.py:469: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
C:\Users\annam\AppData\Local\anaconda3\lib\inspect.py:469: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
C:\Users\annam\AppData\Local\anaconda3\lib\inspect.py:469: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000

In [18]:
dff1

NameError: name 'dff1' is not defined

In [40]:
df1 =  pd.DataFrame({'X1':[1, 2, 4, 5, 6], 'X2':[4, 8, 12, 16, 20], 'new': [12, 34,56, 45, 31]})
print(df1)

   X1  X2  new
0   1   4   12
1   2   8   34
2   4  12   56
3   5  16   45
4   6  20   31


In [41]:
df1[df1.X1 > 3]

X1  X2  new
2   4  12   56
3   5  16   45
4   6  20   31

In [42]:
df1['A'] = ['one', 'one', 'two', 'three', 'four']
df1

X1  X2  new      A
0   1   4   12    one
1   2   8   34    one
2   4  12   56    two
3   5  16   45  three
4   6  20   31   four

In [43]:
df1.A.isin(['one'])

0     True
1     True
2    False
3    False
4    False
Name: A, dtype: bool

In [44]:
df1[df1.A.isin(['one', 'three'])]

X1  X2  new      A
0   1   4   12    one
1   2   8   34    one
3   5  16   45  three

In [30]:
# change the value

df1.iat[1, 2] = 5
print(df1)

   X1  X2  new      A
0   1   4   12    one
1   2   8    5    one
2   4  12   56    two
3   5  16   45  three
4   6  20   31   four


In [45]:
# missing data

df1.X2[2], df1.X1[3] = None, None
print(df1)

    X1    X2  new      A
0  1.0   4.0   12    one
1  2.0   8.0   34    one
2  4.0   NaN   56    two
3  NaN  16.0   45  three
4  6.0  20.0   31   four


C:\Users\annam\AppData\Local\Temp\ipykernel_51760\1296098772.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.X2[2], df1.X1[3] = None, None


In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      4 non-null      float64
 1   X2      4 non-null      float64
 2   new     5 non-null      int64  
 3   A       5 non-null      object 
dtypes: float64(2), int64(1), object(1)
memory usage: 288.0+ bytes


In [34]:
df1.isnull() # null - no value

X1     X2    new      A
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3   True  False  False  False
4  False  False  False  False

In [35]:
df1.isna() # na- not a number

X1     X2    new      A
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3   True  False  False  False
4  False  False  False  False

In [36]:
df1.isna().sum()

X1     1
X2     1
new    0
A      0
dtype: int64

In [38]:
# dropping na values

print(df1.dropna(inplace = False)) # false it will not make any changes in orginal frame
print(df1)

    X1    X2  new     A
0  1.0   4.0   12   one
1  2.0   8.0    5   one
4  6.0  20.0   31  four
    X1    X2  new      A
0  1.0   4.0   12    one
1  2.0   8.0    5    one
2  4.0   NaN   56    two
3  NaN  16.0   45  three
4  6.0  20.0   31   four


In [39]:
(df1.dropna(inplace = True)) # True it will  make changes in orginal frame
print(df1)

    X1    X2  new     A
0  1.0   4.0   12   one
1  2.0   8.0    5   one
4  6.0  20.0   31  four


In [46]:
df1 # create new dataframe

X1    X2  new      A
0  1.0   4.0   12    one
1  2.0   8.0   34    one
2  4.0   NaN   56    two
3  NaN  16.0   45  three
4  6.0  20.0   31   four

In [47]:
# filling all na values

df1.fillna(value = 100, inplace = False)

X1     X2  new      A
0    1.0    4.0   12    one
1    2.0    8.0   34    one
2    4.0  100.0   56    two
3  100.0   16.0   45  three
4    6.0   20.0   31   four

In [49]:
# only one columns
df1.X1.fillna(value = 100, inplace = False)


0      1.0
1      2.0
2      4.0
3    100.0
4      6.0
Name: X1, dtype: float64

In [51]:
# multiple columns
df1.loc[:,['X1', 'X2']].fillna(value = 500, inplace = False)

X1     X2
0    1.0    4.0
1    2.0    8.0
2    4.0  500.0
3  500.0   16.0
4    6.0   20.0

# operation in pandas

In [2]:
import pandas as pd
x1 = [11, 12, 13, 14, 15]
x2 = [21, 22, 23, 24, 25]
x3 = list(range(5))

dff1 = pd.DataFrame({'X1': x1, 'X2': x2, 'X3': x3})
print(dff1)

   X1  X2  X3
0  11  21   0
1  12  22   1
2  13  23   2
3  14  24   3
4  15  25   4


In [53]:
dff1.X1 + dff1.X2

0    32
1    34
2    36
3    38
4    40
dtype: int64

In [54]:
dff1.X1 + dff1.X2 * dff1.X3

0     11
1     34
2     59
3     86
4    115
dtype: int64

In [3]:
dff1['new'] = dff1.X1 + dff1.X2 * dff1.X3+5
print(dff1)

   X1  X2  X3  new
0  11  21   0   16
1  12  22   1   39
2  13  23   2   64
3  14  24   3   91
4  15  25   4  120


In [57]:
dff1.X1.mean()

13.0

In [58]:
 dff1.mean()

X1     13.0
X2     23.0
X3      2.0
new    66.0
dtype: float64

In [59]:
dff1.sum()

X1      65
X2     115
X3      10
new    330
dtype: int64

In [60]:
dff1.max()

X1      15
X2      25
X3       4
new    120
dtype: int64

In [61]:
dff1.min()

X1     11
X2     21
X3      0
new    16
dtype: int64

In [62]:
dff1.count()

X1     5
X2     5
X3     5
new    5
dtype: int64

In [63]:
dff1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      5 non-null      int64
 1   X2      5 non-null      int64
 2   X3      5 non-null      int64
 3   new     5 non-null      int64
dtypes: int64(4)
memory usage: 288.0 bytes


In [65]:
dff1.dtypes

X1     int64
X2     int64
X3     int64
new    int64
dtype: object

In [66]:
dff1.apply(lambda x : x.max() + x.min()) # max of x1 + min of X1

X1      26
X2      46
X3       4
new    136
dtype: int64

In [67]:
dff1.apply(lambda x : x.max() + x.min(), axis = 1) # axis 1 = row , axis 0 = column

0     21
1     40
2     66
3     94
4    124
dtype: int64

In [70]:
print(dff1.X1)
dff1.X1.apply(lambda x : x + 7)

0    11
1    12
2    13
3    14
4    15
Name: X1, dtype: int64


0    18
1    19
2    20
3    21
4    22
Name: X1, dtype: int64

In [71]:
def manipulate(x):
    if x > 2:
        return 'yes'
    else:
        return 'no'

In [73]:
print(dff1)
dff1.X1.apply(lambda x : manipulate(x)) # using other function

   X1  X2  X3  new
0  11  21   0   16
1  12  22   1   39
2  13  23   2   64
3  14  24   3   91
4  15  25   4  120


0    yes
1    yes
2    yes
3    yes
4    yes
Name: X1, dtype: object

In [74]:
# another way

dff1.X1.apply(manipulate)

0    yes
1    yes
2    yes
3    yes
4    yes
Name: X1, dtype: object

In [4]:
print(dff1)

   X1  X2  X3  new
0  11  21   0   16
1  12  22   1   39
2  13  23   2   64
3  14  24   3   91
4  15  25   4  120


In [7]:
import numpy as np

dff1.X2.apply(np.sqrt)

0    4.582576
1    4.690416
2    4.795832
3    4.898979
4    5.000000
Name: X2, dtype: float64

In [12]:
#multiple columns

dff1.loc[:,['X1','X2']].apply(lambda x : x + 2)

X1  X2
0  13  23
1  14  24
2  15  25
3  16  26
4  17  27

In [13]:
# appling changes according to multiple columns

dff1.apply(lambda x : x.X1 + x.X2, axis = 1)

0    32
1    34
2    36
3    38
4    40
dtype: int64

# date and times

In [3]:
from datetime import date

date.fromisoformat('2023-06-15') #yyyy-mm-dd

datetime.date(2023, 6, 15)

In [4]:
byt = bytes(3)
print(type(byt))
print(byt)

<class 'bytes'>
b'\x00\x00\x00'


In [5]:
# we can replace the dates

d = date(2023, 6, 11)
d.replace(day = 15)

datetime.date(2023, 6, 15)

In [6]:
# date.isocalendar()

# iso always started on monday , it's not shows the decimal point it either 52 or 53 full weeks

date(2003, 12, 29).isocalendar()

datetime.IsoCalendarDate(year=2004, week=1, weekday=1)

In [6]:
# date.isoformat

date(2023,6,15).isoformat()

'2023-06-15'

In [26]:
# time delta function

from datetime import datetime, timedelta

date_time_str = datetime.now()
print(str(date_time_str))

y = date_time_str + timedelta(days = 730) # after two years
str(y)

2023-06-15 20:19:28.351886


'2025-06-14 20:19:28.351886'

In [27]:
import time

date.fromtimestamp(time.time())


datetime.date(2023, 6, 15)

In [36]:
import datetime

date_time_str = '2023-06-15 19:50:57.403772'

date_time_obj = datetime.datetime.strptime(date_time_str, '%Y-%m-%d %H:%M:%S.%f')

print('date :', date_time_obj.date())
print('time:', date_time_obj.time())
print('datetime :', date_time_obj)



date : 2023-06-15
time: 19:50:57.403772
datetime : 2023-06-15 19:50:57.403772


In [39]:
date_time_str = '2019-jan-08 09:12:23'

date_time_obj = datetime.datetime.strptime(date_time_str , '%Y-%b-%d %H:%M:%S') # b- abbreviated jan

print(date_time_obj) # strp - it convert string to date_time object

2019-01-08 09:12:23


In [40]:
# formatting examples

print(date_time_obj.strftime('%Y-%b-%d')) # b = short of month
print(date_time_obj.strftime('%a-%b-%y')) # a = short of weekend
print(date_time_obj.strftime('%a-%b-%y %I:%M:%S %p')) # I = 12 hr clock
print(date_time_obj.strftime('date is %D, and time is %T'))
print(date_time_obj.strftime('%A-%B-%Y')) # strf - it convert date_time to string object

2019-Jan-08
Tue-Jan-19
Tue-Jan-19 09:12:23 AM
date is 01/08/19, and time is 09:12:23
Tuesday-January-2019


In [2]:
from random import randrange
from datetime import timedelta, datetime

def random_date(start, end):
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = randrange(int_delta)
    return start + timedelta(seconds=random_second)

d1 = datetime.strptime('1/1/1998 1:30 PM', '%m/%d/%Y %I:%M %p')
d2 = datetime.strptime('1/1/2020 4:50 AM', '%m/%d/%Y %I:%M %p')
print(random_date(d1, d2))

2010-08-21 16:10:17


In [4]:
d2 = datetime.strptime('1/1/1998 1:30 PM', '%m/%d/%Y %I:%M %p')
d3 = datetime.strptime('1/1/2020 4:50 AM', '%m/%d/%Y %I:%M %p')
print(random_date(d2, d3))

2018-06-12 02:07:44


In [8]:
date_time = []

for i in range(20):
    date_time.append(random_date(d2, d3))
    
(date_time)    

[datetime.datetime(2012, 6, 29, 8, 46, 59),
 datetime.datetime(2000, 1, 25, 19, 38, 50),
 datetime.datetime(2015, 3, 15, 10, 7, 15),
 datetime.datetime(2004, 8, 30, 10, 43, 57),
 datetime.datetime(2011, 12, 20, 22, 0, 14),
 datetime.datetime(2005, 7, 31, 14, 41, 13),
 datetime.datetime(2001, 9, 5, 13, 15, 43),
 datetime.datetime(2014, 9, 25, 7, 32, 40),
 datetime.datetime(2018, 2, 11, 2, 1, 11),
 datetime.datetime(2009, 12, 2, 23, 43, 2),
 datetime.datetime(2011, 12, 7, 8, 55, 13),
 datetime.datetime(1998, 1, 13, 7, 37, 46),
 datetime.datetime(2008, 4, 14, 0, 51, 44),
 datetime.datetime(2005, 10, 24, 13, 13, 15),
 datetime.datetime(2001, 10, 23, 5, 15, 56),
 datetime.datetime(2001, 11, 19, 17, 37, 24),
 datetime.datetime(2004, 2, 14, 19, 2, 45),
 datetime.datetime(2019, 7, 20, 13, 52, 27),
 datetime.datetime(2004, 3, 14, 14, 30, 16),
 datetime.datetime(2016, 3, 1, 0, 8, 11)]

In [11]:
# generating random date string format

date_formats = []

for i in range(20):
    year_month_day = str(randrange(1998, 2023)) + '-' + str(randrange(1, 12)) + '-' + str(randrange(1, 31))
    date_formats.append(year_month_day)
    
date_formats    

['1998-9-7',
 '2019-3-11',
 '2011-7-15',
 '2012-6-8',
 '2012-3-11',
 '2008-2-22',
 '2021-4-20',
 '2008-8-12',
 '2018-2-28',
 '2018-11-4',
 '2011-3-5',
 '2017-7-30',
 '2011-2-6',
 '2014-3-30',
 '2002-10-18',
 '2006-4-15',
 '2001-4-1',
 '2005-9-16',
 '2006-8-14',
 '2010-11-29']

In [12]:
import pandas as pd

df = pd.DataFrame({'first_col' : date_time , 'second_col' : date_formats})
df.head() # it shows first 5

first_col second_col
0 2012-06-29 08:46:59   1998-9-7
1 2000-01-25 19:38:50  2019-3-11
2 2015-03-15 10:07:15  2011-7-15
3 2004-08-30 10:43:57   2012-6-8
4 2011-12-20 22:00:14  2012-3-11

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   first_col   20 non-null     datetime64[ns]
 1   second_col  20 non-null     object        
dtypes: datetime64[ns](1), object(1)
memory usage: 448.0+ bytes


In [14]:
df.dtypes

first_col     datetime64[ns]
second_col            object
dtype: object

In [16]:
df.sort_values(by = ['first_col'], inplace = False).head(10)

first_col  second_col
11 1998-01-13 07:37:46   2017-7-30
1  2000-01-25 19:38:50   2019-3-11
6  2001-09-05 13:15:43   2021-4-20
14 2001-10-23 05:15:56  2002-10-18
15 2001-11-19 17:37:24   2006-4-15
16 2004-02-14 19:02:45    2001-4-1
18 2004-03-14 14:30:16   2006-8-14
3  2004-08-30 10:43:57    2012-6-8
5  2005-07-31 14:41:13   2008-2-22
13 2005-10-24 13:13:15   2014-3-30

In [17]:
df.sort_values(by = ['first_col'], inplace = False , ascending = False).head(10)

first_col  second_col
17 2019-07-20 13:52:27   2005-9-16
8  2018-02-11 02:01:11   2018-2-28
19 2016-03-01 00:08:11  2010-11-29
2  2015-03-15 10:07:15   2011-7-15
7  2014-09-25 07:32:40   2008-8-12
0  2012-06-29 08:46:59    1998-9-7
4  2011-12-20 22:00:14   2012-3-11
10 2011-12-07 08:55:13    2011-3-5
9  2009-12-02 23:43:02   2018-11-4
12 2008-04-14 00:51:44    2011-2-6

In [19]:
df.sort_values(by = ['first_col', 'second_col'], inplace = False , ascending = True).head(10)

first_col  second_col
11 1998-01-13 07:37:46   2017-7-30
1  2000-01-25 19:38:50   2019-3-11
6  2001-09-05 13:15:43   2021-4-20
14 2001-10-23 05:15:56  2002-10-18
15 2001-11-19 17:37:24   2006-4-15
16 2004-02-14 19:02:45    2001-4-1
18 2004-03-14 14:30:16   2006-8-14
3  2004-08-30 10:43:57    2012-6-8
5  2005-07-31 14:41:13   2008-2-22
13 2005-10-24 13:13:15   2014-3-30

# data structure in python

In [30]:
# array is defined as storage or container or similar items placed in contiguous memory location

# homogenous array will contain the element same data type
# hetrogenous array will not contain the same data type

 # typecode available for array

# 'i' = integer, 2 bytes
# 'f' = float, 4 bytes
# 'd' = double filar type, 8 bytes
# 'u' = unicode character, 2 bytes



In [34]:
# creating an array

import array as myarray

arr = myarray.array('i',[1, 2, 3])
arr1 = myarray.array('f',[1.1, 2.3, 3.5])
arr2 = myarray.array('u',['a', 'b', 'c', 'd'])

# typecodes
print(arr.typecode)
print(arr1.typecode)
print(arr2.typecode)

print(arr)
print(arr1)
print(arr2)


i
f
u
array('i', [1, 2, 3])
array('f', [1.100000023841858, 2.299999952316284, 3.5])
array('u', 'abcd')


In [35]:
# length of an array

print(len(arr))
print(len(arr1))
print(len(arr2))

3
3
4


In [39]:
for i in range(0,len(arr)):
    print(arr[i], end = ' ')
print('\n')
for i in range(0,len(arr1)):
    print(arr1[i], end = ' ')
print('\n')
for i in range(0,len(arr2)):
    print(arr2[i], end = ' ')

1 2 3 

1.100000023841858 2.299999952316284 3.5 

a b c d 

In [41]:
# accessing the elements in array by index

x = list(range(1,50))
new_array= myarray.array('i', x)

for i in range(0, len(new_array)):
    print(new_array[i], end= ' ')
    
print('\n')
print(new_array[20])

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

21


In [51]:
# adding the elements in the array

new_array = myarray.array('i', [3, 4, 5, 6, 7, 8, 9])
print(new_array)
print(new_array.typecode)

new_array.insert(0, 2)
new_array.insert(0, 1)
print(new_array)

new_array.append(11)
print(new_array)

for i in range(0,len(new_array)):
    print(new_array[i], end = " ")




array('i', [3, 4, 5, 6, 7, 8, 9])
i
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 11])
1 2 3 4 5 6 7 8 9 11 

In [53]:
# update

new_array = myarray.array('i', [3, 4, 5, 7, 7, 8, 9])

new_array[3] = 6
print(new_array)

array('i', [3, 4, 5, 6, 7, 8, 9])


In [55]:
# delete

new_array.pop(4)
print(new_array)

new_array.remove(5)
print(new_array)


array('i', [3, 4, 5, 6, 9])
array('i', [3, 4, 6, 9])


In [58]:
# slicing operation

x = list(range(1,100,3))
arr = myarray.array('i', x)
print(arr)

arr0 = arr[10:20]
print(arr0)

arr1 = arr[10:-10]
print(arr1)



array('i', [1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])
array('i', [31, 34, 37, 40, 43, 46, 49, 52, 55, 58])
array('i', [31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67])


In [62]:
# searcch operation in an array using index

x = arr.index(76)
print(x)

y = arr[x]
y

25


76

In [73]:
# sorting operation

x = list(range(1,100,3))
arr = myarray.array('i', x)
arr1 = arr.tolist()
print(arr1)



[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]


In [78]:
arr1.sort()
print(arr1, end= ' ')

x = sorted(arr1)
print(x)

y= arr1.sort(reverse = True)
print(arr1, end= ' ')

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97] [1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]
[97, 94, 91, 88, 85, 82, 79, 76, 73, 70, 67, 64, 61, 58, 55, 52, 49, 46, 43, 40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10, 7, 4, 1] 

In [85]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print('\n')

# creating an array with zeros

zeros = np.zeros((2,2))
print(zeros)
print('\n')

ones = np.ones((2,2))
print(ones)
print('\n')

x = [1, 2, 3]

dia = np.diag(x)
print(dia)




[1 2 3 4 5]


[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [93]:
# creating an array with constant values

const = np.full((3,3), 7)
print(const)
print('\n')

# create an idendity matrix

iden = np.eye(3)
print(iden)

print('\n')

# random values

rand = np.random.random((2,2))
print(rand)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0.33985802 0.94409703]
 [0.80240137 0.99608466]]


In [102]:
# 1-D, 2-D, 3-D, multi-dim

zerod = np.array(1)
print(zerod)
print('\n')
oned= np.array((1,1))
print(oned)
print('\n')

twod = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print(twod)
print('\n')

threed = np.array([[[1, 2, 3],[3, 4, 5]],[[5, 6, 7], [7, 8, 9]]])
print(threed)

print('\n')

multid = np.array([1, 2, 3, 4, 5], ndmin= 5)
print(multid)

print('\n')



1


[1 1]


[[1 2 3 4 5]
 [1 2 3 4 5]]


[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


[[[[[1 2 3 4 5]]]]]




In [99]:
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)
print(multid.ndim)


1
2
3
5


In [105]:
# curd operation

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

# update
arr[7] = 99
print(arr)

# delete

x = np.delete(arr, 6)
x

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7 99  9 10]


array([ 1,  2,  3,  4,  5,  6, 99,  9, 10])

In [107]:
# searching the elements

x = np.where(arr == 7)
print(x)

y = arr[6]
y

(array([6], dtype=int64),)


7

In [108]:
# sort

x = np.sort(arr)
x

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 99])

In [116]:
# mathematical operation

a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

# add
add = np.add(a,b)
print(add)
print('\n')

# sub
sub = np.subtract(a,b)
print(sub)
print('\n')

# multiply
mult = np.multiply(a,b)
print(mult)
print('\n')

# division

div = np.divide(a,b)
print(div)
print('\n')

# square root

sqrt1 = np.sqrt(a)
print(sqrt1)
sqrt2 = np.sqrt(b)
print(sqrt2)
print('\n')

# transpose

x = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

tran = np.transpose(x)
print(tran)


[[5 7 9]]


[[-3 -3 -3]]


[[ 4 10 18]]


[[0.25 0.4  0.5 ]]


[[1.         1.41421356 1.73205081]]
[[2.         2.23606798 2.44948974]]


[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [3]:
lis = [12, 34, 56, 34, 67, 98, 100]
lis[0]

12

In [6]:
for i in lis:
    print(i)

12
34
56
34
67
98
100


In [7]:
dir(i)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes

In [3]:
class student:
    def __init__(self,f_name,l_name):
        self.f_name = f_name
        self.l_name = l_name
    
    def __str__(self):
        return(f'first name is {self.f_name} and last name is {self.l_name}.')

a = student('annamalai', 'subramani')

print(a)

first name is annamalai and last name is subramani.
